import 'dotenv/config';
import OpenAI from 'openai';
import {
  ResponseInputItem,
  Tool,
} from 'openai/resources/responses/responses.js';

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// 1. Define a list of callable tools for the model
const tools: Tool[] = [
  {
    type: 'function',
    name: 'get_horoscope',
    description: "Get today's horoscope for an astrological sign.",
    parameters: {
      type: 'object',
      properties: {
        sign: {
          type: 'string',
          description: 'An astrological sign like Taurus or Aquarius',
        },
      },
      required: ['sign'],
      additionalProperties: false,
    },
    strict: true,
  },
];

function getHoroscope(sign: string) {
  return `${sign}: Next Tuesday you will befriend a baby otter.`;
}

// Create a running input list we will add to over time
let input: ResponseInputItem[] = [
  { role: 'user', content: 'What is my horoscope? I am an Aquarius.' },
];

async function main() {
  // 2. Prompt the model with tools defined
  let response = await client.responses.create({
    model: 'gpt-5.4-mini',
    tools,
    input,
  });

  // Preserve model output for the next turn
  input.push(...(response.output as ResponseInputItem[]));

  for (const item of response.output) {
    if (item.type !== 'function_call') continue;

    if (item.name === 'get_horoscope') {
      // 3. Execute the function logic for get_horoscope
      const { sign } = JSON.parse(item.arguments);
      const horoscope = getHoroscope(sign);

      // 4. Provide function call results to the model
      input.push({
        type: 'function_call_output',
        call_id: item.call_id,
        output: horoscope,
      });
    }
  }

  console.log('Final input:');
  console.log(JSON.stringify(input, null, 2));

  response = await client.responses.create({
    model: 'gpt-5.5',
    instructions: 'Respond only with a horoscope generated by a tool.',
    tools,
    input,
  });

  // 5. The model should be able to give a response!
  console.log('Final output:');
  console.log(response.output_text);
}

main();
